version: "3.8"
services:
    database:
        image: postgres:14.2-alpine3.15
        container_name: result_database
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    db_data:
