version: "3.8"
services:
  server:
    container_name: results_server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static
    environment:
      #
      ENVIRONMENT: ${ENVIRONMENT}
      SECRET_KEY: ${SECRET_KEY}
      #
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: [ "sh", "./docker-entrypoint.sh" ]
  nginx:
    container_name: results_nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - server
    volumes:
      - static:/usr/share/nginx/static
    command: [ "sh", "./docker-entrypoint.sh" ]

volumes:
  static:
